### PR TITLE
Prepare new release, build with AlmaLinux, drop deprecated meta-packages.

### PR DESCRIPTION
**Pull request by gwarf**
Prepare new release, build with AlmaLinux, drop deprecated meta-packages.
This PR/documentation assumes that we will always build/release all the meta-packages for every new GitHub tag/release.
The packages versions and the tag are currently aligned, but in the future we could expect that they could diverge/no more be synchronised if only one package is updated.
### Changed

- emi-bdii-site 1.1.0: update and package documentation, build using GitHub actions (#2) (Baptiste Grenier)
- emi-bdii-top 1.1.0: update and package documentation, build using GitHub actions (#2) (Baptiste Grenier)
- emi-resource-information-service 1.1.0: update and package documentation, build using GitHub actions (#2) (Baptiste Grenier)

### CODE REVIEW

**Comment by gwarf** [comment]
The metpackage installations are failing on CentOS 8 and 9 as those files should be taken from UMD, and currently it doesn't exit.
As it's "only" meta packages, I'm not sure how much we should care about just trying to install them.
Or we need to find a way to bootstrap or manage this...

**Comment by gwarf** [comment]
@enolfc , @andrea-manzi have you any suggestion? Should we just skip the install steps?

**Comment by gwarf** [comment]
And on CentOS 7 it also fails: https://github.com/EGI-Federation/gridinfo-meta-packages/actions/runs/4386846330/jobs/7681431197#step:4:402

```
Error: Package: glite-BDII_site-3.2.6-1.el7.noarch (/glite-BDII_site-3.2.6-1.el7.noarch)
           Requires: glite-info-provider-release >= 1.0.1
```

**Comment by gwarf** [comment]
The status of those failing packages have to be checked, not sure how much they are still relevant/required.

**Comment by gwarf** [comment]
I've stopped building them, they can probably be archived in the git history, no?

**Comment by gwarf** [comment]
A bit better:
Screenshot 2023-03-10 at 18 51 40

**Comment by gwarf** [comment]
Duh, it seems something broke, I'm no more able to build any package: https://github.com/EGI-Federation/gridinfo-meta-packages/actions/runs/4417366287/jobs/7742964260#step:4:373

I see the same error locally, and http://vault.centos.org/centos/7/os/Source/repodata/repomd.xml returns error. Not sure if it's an issue with the container or this repo :/

`rm /etc/yum.repos.d/CentOS-Sources.repo` allows to build, but it doesn't look like a great workaround...

**Comment by gwarf** [comment]
Seems they fixed and issue: https://lists.centos.org/pipermail/centos/2023-March/896760.html
Building is now working again.

**Comment by gwarf** [comment]
With the latest changes, I assume that we will always build/release all the meta-packages for every new GitHub tag/release.
Currently I aligned the packages versions and the tag, but in the future we could expect that they could diverge/no more be synchronised if only one package is updated. Let's see, maybe it will stay very static.
The other solution would be to split in 3 dedicated repos, but I would prefer to avoid the overhead, if possible.
Or maybe someone is having a suggestion/alternative?

**Review by enolfc — COMMENTED** [review]
👍 
I assume the problem with Alma will be corrected once we have UMD for it?

**Comment by gwarf** [comment]
So the issue is that install fails due to missing dependencies, that indeed should be taken from UMD5, cf #4.

**Pull request merged**
